package CatProducerTest;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import CatProducer.CatProducer;
import org.junit.Test;
import static org.junit.Assert.*;

public class CatProducerTest {
    @Test public void testAppHasAGreeting() {
        CatProducer classUnderTest = new CatProducer();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
